### ISSUE TITLE
how can i create a url 

### ISSUE THREAD

**Issue by sushipan** [naxos/SMBClient#1]
Thank you for your smbclient 
When  I access the file like this smb://192.168.0.102/hello/sample.mp4 ,every goes right,
but if I access the file like this smb://192.168.0.102/hello smb/sample.mp4 ,it makes issues

**Comment by schamar** [comment]
Hi SushiPan, can you define "issues"? Thanks.

**Comment by schamar** [comment]
Also, the API doesn't use URLs. So why would you create one in the first place?

**Comment by sushipan** [comment]
Thank you for your help.  And sorry, i mean i can not create a right file url to play with vlc video player

**Comment by schamar** [comment]
Still can't see what this has to do with SMBClient. Please provide code sample.

**Comment by sushipan** [comment]
Something like this 
SMBFile *smbFile ;// I get the  smbFile use SMBClient
NSString urlString = [NSString stringWithFormat:@"smb://%@/%@%@",smbFile.share.server.host,smbFile.share.name,smbFile.path];
NSUrl *url = [NSURL URLWithString:urlString];
AVPlayerItem *playerItem = [[AVPlayerItem alloc] initWithURL:url];
AVPlayer *player = [[AVPlayer alloc] init];
[player replaceCurrentItemWithPlayerItem:playerItem];

AVPlayerLayer *playerLayer = [AVPlayerLayer playerLayerWithPlayer:player];
playerLayer.frame = CGRectMake(0, 0, self.view.bounds.size.width, 500);
[self.view.layer addSublayer:playerLayer];
[player play];

**Comment by sushipan** [comment]
And i use VLC player to do this, because VLC support SMB Protocol  
I use the VLC Nightly build
https://nightlies.videolan.org/build/iOS/

**Comment by sushipan** [comment]
```
  SMBFile *smbFile ;// I get the smbFile use SMBClient
  NSString urlString = [NSString    stringWithFormat:@"smb://%@/%@%@",smbFile.share.server.host,smbFile.share.name,smbFile.path];
 NSUrl *url = [NSURL URLWithString:urlString];
 VLCMedia *media2 =  [VLCMedia mediaWithURL:url];
 VLCMediaList *mediaList = [[VLCMediaList alloc]init];
 [mediaList insertMedia:media2 atIndex:0];

 mediaListPlayer = [[VLCMediaListPlayer alloc] initWithDrawable:movieView];
 mediaListPlayer.mediaPlayer.delegate = self;
 mediaListPlayer.repeatMode = VLCRepeatCurrentItem;
 mediaListPlayer.mediaList = mediaList;
 [mediaListPlayer playItemAtIndex:0];
```

**Comment by schamar** [comment]
Your issue is unrelated to this library. However, your urlString is not properly encoded. Use something like:

NSString *path = [smbFile.path stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLPathAllowedCharacterSet]];

and then your code:

NSString urlString = [NSString    stringWithFormat:@"smb://%@/%@%@",smbFile.share.server.host,smbFile.share.name,**path**];
NSUrl *url = [NSURL URLWithString:urlString];

Also treat the share name the same way...
