### ISSUE TITLE
Crashing when using WPSDNP Printer

### ISSUE THREAD

**Issue by ppogra23** [naxos/SMBClient#10]
Hello,
We have integrated SMBClient in iOS application and app is using WPSDNP printer for printing and it's working but sometime we are getting crashes from user and looks like it's originated from SMB lib. Below are crashes trace, please advise (all crashes are on iOS 11).
Frist - 
`
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000010ba98040
Crashed: smb_file_queue_/DS620/2x2x6s/2018-04-01_191104.jpg
0  libsystem_platform.dylib       0x183239a1c _platform_memmove + 108
1  libsystem_malloc.dylib         0x183169fd4 szone_realloc + 2560
2  libsystem_malloc.dylib         0x183169fd4 szone_realloc + 2560
3  libsystem_malloc.dylib         0x18316956c malloc_zone_realloc + 180
4  libsystem_malloc.dylib         0x1831693f0 realloc + 284
5  SMBClient                      0x1057a0900 netbios_session_packet_recv + 132
6  SMBClient                      0x1057a3a78 smb_session_recv_msg + 36
7  SMBClient                      0x1057a15e8 smb_fwrite + 248
8  SMBClient                      0x105795038 __26-[SMBFile write:progress:]_block_invoke + 764
9  libdispatch.dylib              0x182f9aa54 _dispatch_call_block_and_release + 24
10 libdispatch.dylib              0x182f9aa14 _dispatch_client_callout + 16
11 libdispatch.dylib              0x182fa496c _dispatch_queue_serial_drain$VARIANT$mp + 528
12 libdispatch.dylib              0x182fa52fc _dispatch_queue_invoke$VARIANT$mp + 340
13 libdispatch.dylib              0x182fa5d20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
14 libdispatch.dylib              0x182fae03c _dispatch_workloop_worker_thread$VARIANT$mp + 644
15 libsystem_pthread.dylib        0x183242f1c _pthread_wqthread + 932
16 libsystem_pthread.dylib        0x183242b6c start_wqthread + 4
`
Second - 
`
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000001a1b5e7cd81
Crashed: smb_share_queue_Hot Folder Printers
0  SMBClient                      0x1008e5004 smb_session_file_remove + 12
1  SMBClient                      0x1008e52b8 smb_fclose + 44
2  SMBClient                      0x1008d1424 __38-[SMBShare closeFile:path:completion:]_block_invoke + 232
3  libdispatch.dylib              0x184b06a54 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x184b06a14 _dispatch_client_callout + 16
5  libdispatch.dylib              0x184b1096c _dispatch_queue_serial_drain$VARIANT$mp + 528
6  libdispatch.dylib              0x184b112fc _dispatch_queue_invoke$VARIANT$mp + 340
7  libdispatch.dylib              0x184b11d20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
8  libdispatch.dylib              0x184b1a03c _dispatch_workloop_worker_thread$VARIANT$mp + 644
9  libsystem_pthread.dylib        0x184daef1c _pthread_wqthread + 932
10 libsystem_pthread.dylib        0x184daeb6c start_wqthread + 4
`
Third -

`
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000001c0018
Crashed: smb_share_queue_Hot Folder Printers
0  SMBClient                      0x100edcb10 smb_fstat + 424
1  SMBClient                      0x100edcb00 smb_fstat + 408
2  SMBClient                      0x100ec7e6c -[SMBShare _stat:] + 116
3  SMBClient                      0x100ec4c54 __37-[SMBShare openFile:mode:completion:]_block_invoke + 416
4  libdispatch.dylib              0x1868aaa54 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x1868aaa14 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1868b496c _dispatch_queue_serial_drain$VARIANT$mp + 528
7  libdispatch.dylib              0x1868b52fc _dispatch_queue_invoke$VARIANT$mp + 340
8  libdispatch.dylib              0x1868b5d20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
9  libdispatch.dylib              0x1868be03c _dispatch_workloop_worker_thread$VARIANT$mp + 644
10 libsystem_pthread.dylib        0x186b52f1c _pthread_wqthread + 932
11 libsystem_pthread.dylib        0x186b52b6c start_wqthread + 4
`

Fourth - 

`
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
Crashed: smb_share_queue_Hot Folder Printers
0  SMBClient                      0x1051f4e98 smb_session_share_get + 8
1  SMBClient                      0x1051f509c smb_fopen + 48
2  SMBClient                      0x1051e0d08 __37-[SMBShare openFile:mode:completion:]_block_invoke + 596
3  libdispatch.dylib              0x182f9aa54 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x182f9aa14 _dispatch_client_callout + 16
5  libdispatch.dylib              0x182fa496c _dispatch_queue_serial_drain$VARIANT$mp + 528
6  libdispatch.dylib              0x182fa52fc _dispatch_queue_invoke$VARIANT$mp + 340
7  libdispatch.dylib              0x182fa5d20 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 404
8  libdispatch.dylib              0x182fae03c _dispatch_workloop_worker_thread$VARIANT$mp + 644
9  libsystem_pthread.dylib        0x183242f1c _pthread_wqthread + 932
10 libsystem_pthread.dylib        0x183242b6c start_wqthread + 4
`

**Comment by schamar** [comment]
Can you provide some code?

**Comment by schamar** [comment]
Not followed up
