### ISSUE TITLE
support concurrence donload？

### ISSUE THREAD

**Issue by ViterbiDevelopment** [naxos/SMBClient#14]
this code should crash！

for (int i = 0;i<2;i++){

[smfile open:SMBFileModeRead completion:^(NSError * _Nullable error) {
        
        [smfile read:12000 progress:^BOOL(unsigned long long bytesReadTotal, NSData * _Nullable data, BOOL complete, NSError * _Nullable error) {
            
            return YES;
        }];
        
    }];

}

**Comment by schamar** [comment]
Why? Please detail your motivation. While the current implementation might not be ideal, there are several ways to handle a second call to SMBFile:open and crashing is probably not the best option.

**Comment by ViterbiDevelopment** [comment]
I want to download two SMB file at some time.but it crash.

**Comment by ViterbiDevelopment** [comment]
for examples,a user download a big file, this file is downloading.a few minutes later, user to download other file.but last file is not finish.

**Comment by schamar** [comment]
In this case, use two instances of SMBFile rather than one.

**Comment by ViterbiDevelopment** [comment]
I have two cells, and every cell has SMBFile.when I click cell it should be download it .when I click one of them and then click another one.it should be crash eveytime.
the crash info:
malloc: *** mach_vm_map(size=1712078848) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug

**Comment by schamar** [comment]
Sorry, I can't help you, if you don't provide a proper test case. Your problem might occur, because table cells are re-used, but that's only wild speculation.

**Comment by schamar** [comment]
Not followed up
