### ISSUE TITLE
Problem:

### ISSUE THREAD

**Issue by 977720641** [naxos/SMBClient#15]
Hello, I recently did a project related to smb file sharing. My problem is: Our recorded video has a specified smb://ip (device ip)/pub on the hardware device server. / Record, this path above, I want to visit this path to get the recorded video, and then to play, how can I achieve this change, iOS side smb is really not understand, I hope you can help me, first thank you.
Only one path, no username and password:
![image](https://user-images.githubusercontent.com/34430844/39792745-cfc3e6ce-5374-11e8-9cb8-d049a29c1849.png).

**Comment by schamar** [comment]
Sorry, can't see in what respect this could be an issue of this project.
