### ISSUE TITLE
Trying to access network share in domain based system/user

### ISSUE THREAD

**Issue by narendra-ct** [naxos/SMBClient#2]
Hi,
I'm trying to access the share with domain based users/system, here i can able to see the list of systems and when i try to login, it throws FAILED.
thanks for the help.

BR,
Narendra.

**Comment by schamar** [comment]
Could you provide code, please.

**Comment by schamar** [comment]
No response. Closed.

**Comment by beks6** [comment]
connecting to a domain based system is possible. But there is a small bug.

This [line](https://github.com/naxos/SMBClient/blob/master/SMBClient/SMBFileServer.m#L83) sets the login creds. But `name` should represent the domain of the server. (check the variable names [here](https://github.com/videolabs/libdsm/blob/1ef10adc3b4f57d4fafc694227c6fcc49b88a0ca/src/smb_session.c#L304))

To solve this temporarily it is necessary to change the `name` at this [line](https://github.com/naxos/SMBClient/blob/master/SMBClient/SMBFileServer.m#L83) to `"domain.com"`

`smb_session_connect` takes than the name of the server and IP

For which serves `group` in init? Maybe you could use it for the domain?
