### ISSUE TITLE
Cant create directory

### ISSUE THREAD

**Issue by assad62** [naxos/SMBClient#3]
Hi,

When i try to create a directory based on the example given, i get the following error:

nable to create the directory: Error Domain=dsm.error Code=3 "SMB error" UserInfo={NSLocalizedDescription=SMB error, NSUnderlyingError=0x60800065bcf0 {Error Domain=nt.error Code=26 "Object path not found" UserInfo={NSLocalizedDescription=Object path not found}}}

Any idea what im doing wrong? I am following the steps as you have mentioned in the read me, everything works other than creating directories and uploading (where i get the same error)

**Comment by schamar** [comment]
Most likely the parent directory doesn't exist (or isn't writable).

**Comment by assad62** [comment]
Correct. Thank you, that was my mistake.
