### ISSUE TITLE
How can I upload a file ? (move a file from one directory to another as NSdata)

### ISSUE THREAD

**Issue by assad62** [naxos/SMBClient#4]
I have a file abc.txt, located at Smb://ShareA/DirA/abc.txt.

I want to move it too Smb://ShareA/DirB. 

How can I achieve this? 

Currently I am getting the NSData of abc.txt from the file download code you have given, and then I create a new File object as:

`SmbFile *newFile= [[SMBFile alloc]initWithPath:/DirB/abc.txt share:ShareA];`

then when I try to open the new file I get the error:

```
`Unable to open the file: Error Domain=dsm.error Code=3 "SMB error" UserInfo={NSLocalizedDescription=SMB error, NSUnderlyingError=0x60000025cdd0 {Error Domain=nt.error Code=26 "Object path not found" UserInfo={NSLocalizedDescription=Object path not found}}}
`
```

I am guessing my initialisation of the file object is not correct. Kindly advise if possible. Thank you

**Comment by schamar** [comment]
remove all the smb://share from your paths. Also, it might help to README.

**Comment by assad62** [comment]
Yeah, i dont have smb://share in the path. That was just as an example. Ill edit the question above. Sorry

I have read the readme, and again downloading works but no success uploading.

**Comment by schamar** [comment]
There's a more or less complete unit test with the project (including file upload). At the beginning of the code, there are constants for host, share, username, password. Initialise them with valid values and run the test.

**Comment by schamar** [comment]
If you have a guest share, leave username and password at nil.

**Comment by assad62** [comment]
Wow. This is super embarrassing. 

Turns out I was passing the wrong path and actually DID have the share appended to the path. 

@schamar many thanks for your time. I should have checked before opening up an issue here. Sorry. 

For anyone who is careless like me, make sure the path of the new file is:

`DirA/FileA and not ShareA/DirA/FileA`

Everything works just fine now.

**Comment by schamar** [comment]
No Problem, glad I could help

**Comment by schamar** [comment]
P.S.: If you want to move a file within the same share, you can also just use the moveTo method of SMBFile. Saves a lot of network traffic.
