### ISSUE TITLE
Renaming Files/Folders

### ISSUE THREAD

**Issue by assad62** [naxos/SMBClient#5]
Hi there, 

Hoping you can help me out here. Im trying to rename a file but im getting the following error:

error Domain=smb.error Code=58 "No such file or directory" UserInfo={NSLocalizedDescription=No such file or directory}

My code is as follows:

Smb *file=[SmbFile alloc]initWithPath: @"1/1.png" share:Desktop];
 [file moveTo:@"2.png" completion:^(NSError * _Nullable error) {
 }];

Any ideas? TIA

**Comment by assad62** [comment]
Ok, just tested at the office on a linux share and every thing works just fine. Im guessing some issues with file permissions on my home machine. 

So closing now. All is good. 

Thank you

**Comment by laoyur** [comment]
hi, I have the same problem
it's not about file system permission as I've succeeded in writing/creating new file

**Comment by damikdk** [comment]
Same, guys. Any ideas how to fix this?
