### ISSUE TITLE
SMBClient over cocoapods?

### ISSUE THREAD

**Issue by beks6** [naxos/SMBClient#7]
Hello,

is it possible to provide this library over cocoapods so it's easier to use it with Swift projects?

**Comment by schamar** [comment]
I can't see a big advantage. Building the project creates a dynamic library, which should be easy to use. But your contribution would be welcome.

**Comment by beks6** [comment]
I see an advantage in providing a heavily wanted library which can be easily imported to Swift projects.
I think it will be helpful for iOS newcomer who never came in touch with ObjC such as me :).

I think at this way your library could reach more people because it's slim and provides the most wanted features.

**Comment by schamar** [comment]
This library was written for our own purposes, and while it's a pleasure to give something back to the open source community, our objective is not to reach as many people as possible. I do agree, that for the particular purpose there are no alternatives out there, and yes, a smooth integration in Swift projects would be a nice addition. However, in my opinion, a thin layer would be needed in order to provide an elegant API for the Swift language. I cannot see, how this can be achieved simply by supporting Cocoapods.

Nevertheless, if you could let us know, what precisely it is that you miss or need (instead of attempting to name the solution), we might give it some consideration.

**Comment by beks6** [comment]
I am currently working on an iOS App, which needs a SMB Connection, to create folder and upload images into it. Your library offers these options. My whole project is based on Swift, as I wrote, I never came in touch with ObjC before.

I'm currently testing around with TOSMBClient (which is also written in ObjC and available on cocoapods), but your library seems to ba a bit tinier and easier to understand/work with it.

I already found and read Apple's docu to use ObjC libraries in Swift projects, but it's a bit of work if u have to do it manually. And if I understand it correctly, cocoapods does all the job in creating BridgingHeaders, so people can use the ObjC methods and funcs easily in Swift.

I am not sure if there is a lot of work for you to do to be able to provide this library over cocoapods, was just asking if it's possible or wether it's worth considering

**Comment by schamar** [comment]
When we officially move towards Swift, we'll do more than just provide a bridging header. So, for now, you'll have to help your self. Don't worry, it's dead simple:

- Let's assume, your Swift-Project is called SwiftSMBClientSample with a directory of the same name, which contains your classes. In this directory create a new file called SwiftSMBClientSample-Bridging-Header.h (right-click directory, "New file..." -> "Header File"). Open it and add the line
`#import <SMBClient/SMBClient.h>`
between the #define and #endif directives
- In the "Build Settings" view "All" and set "Objective-C Bridging Header" in the "Swift Compiler - General" section to "$(SRCROOT)/$(PROJECT_NAME)/$(PROJECT_NAME)-Bridging-Header.h"
- In the "General" section of you project settings add the SMBClient.framework to "Embedded Binaries"

That's it. Enjoy using the framework.

You can try it out in your AppDelegate.swift:

```
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    var discovery: SMBDiscovery?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        discovery = SMBDiscovery.sharedInstance()
        
        discovery?.start(of: SMBDeviceType.fileServer, added: { (device) in
            print("Found file server " + device.host)
        }, removed: { (device) in
            print("File server " + device.host + " disappeared")
        })
        
        return true
    }
```

**Comment by beks6** [comment]
OK thanks, will give it a try. Nice to hear of your plans moving the whole library to Swift

**Comment by schamar** [comment]
No immediate plans :)

**Comment by zeshanmusawar** [comment]
when i connect with mac share file its working but when i connect with the window then File not show and give this error "FilesTableViewController failed to request files: Unable to connect".
