### ISSUE TITLE
Unable to open share

### ISSUE THREAD

**Issue by dcatanoso** [naxos/SMBClient#8]
trying to connect from iPad to Windows 10 share using Objective C on iOS 10.2.

Can connect to file server and find the share (and stepping through all shares are found).
User and password redacted but valid in the code.

However I cannot open the share to write a file. Always get:
 error	NSError *	domain: @"smb.error" - code: 53	0x0000000170050d10

Code snippet is here:

...
    [self.fileServer connectAsUser:@"xxxxx" password:@"xxxxx" completion:^(BOOL guest, NSError *error) {
      if (error)
      {
        NSLog(@"Unable to connect: %@", [error localizedDescription]);
      }
      else if (guest)
      {
        NSLog(@"Logged in as photo");
        success = YES;
      }
      else
      {
        NSLog(@"Logged in");
        success = YES;
      }
      
      if (success)
      {
        [self.fileServer findShare:@"cw001" completion:^(SMBShare *share, NSError *error)
         {
           if (error)
           {
             success = NO;
             NSLog(@"Unable to find the share: %@", error);
           }
           else
           {
             success = YES;
             [share open:^(NSError *error)
              {
                if (error) // this is where the error 53 shows up
                {
                  success = NO;
                  NSLog(@"Unable to open share: %@", error);
                }
                else
                {
                  success = YES;
                  NSLog(@"Opened share '%@'", share.name);
                }
                
                if (success) // share opened
                { ...

Any assistance you can provide would be appreciated.

Thanks

**Comment by anonymouz4** [comment]
Me too:

`Unable to list files: Error Domain=smb.error Code=54 "Not open" UserInfo={NSLocalizedDescription=Not open}`

@dcatanoso Do you got an updates on this?

**Comment by schamar** [comment]
Is SMB v1 disabled on your server?

**Comment by schamar** [comment]
Not followed up.
