### ISSUE TITLE
Create file to wrtie

### ISSUE THREAD

**Issue by rodrigobusata** [naxos/SMBClient#9]
Hi, I didn't find how I can create a new file to write. Is possible do it?

**Comment by schamar** [comment]
You need to open a file in write mode. See Opening Files in the documentation.

**Comment by rodrigobusata** [comment]
I already tried it, but I received this error: "Cannot open write file: Error Domain=dsm.error Code=3 "SMB error" ...NSLocalizedDescription=Object name not found".

**Comment by schamar** [comment]
Make sure the parent directory exists. Check out the unit test for a working example (modify share/user/pass to fit your environment).

**Comment by rodrigobusata** [comment]
It's working now, but I needed to change the open type from "SMBFileModeWrite" to "SMBFileModeReadWrite". Only write mode don't work.

Thank you so much for your help and for your lib, it's very valuable.

**Comment by schamar** [comment]
You're welcome.
From the documentation :) "Use SMBFileModeReadWrite if you want to write to a file (even if you think that you might not require to read it)."
This might actually be a bug (possibly in libdsm).
